version: '3'

services:
  redis:
    image: 'redis:5.0.3'
    command: redis-server
    networks:
      - airflow

  postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - airflow

  webserver:
    image: airflow:latest
    restart: always
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - STAGE=local
      # Airflow specific
      - EXECUTOR=CeleryExecutor
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_BASE_URL=http://localhost:8080
      - FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - ENABLE_REMOTE_LOGGING=False
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - airflow

  flower:
    image: airflow:latest
    restart: always
    depends_on:
      - redis
      - webserver
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - STAGE=local
      # Airflow specific
      - EXECUTOR=CeleryExecutor
      - AIRFLOW_HOME=/usr/local/airflow
    ports:
      - "5555:5555"
    command: flower
    networks:
      - airflow

  scheduler:
    image: airflow:latest
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - STAGE=local
      # Airflow specific
      - EXECUTOR=CeleryExecutor
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_BASE_URL=http://localhost:8080
      - FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - ENABLE_REMOTE_LOGGING=False
    command: scheduler
    networks:
      - airflow

  worker:
    image: airflow:latest
    restart: always
    depends_on:
      - webserver
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - STAGE=local
      # Airflow specific
      - EXECUTOR=CeleryExecutor
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_BASE_URL=http://localhost:8080
      - FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - ENABLE_REMOTE_LOGGING=False
    command: worker
    networks:
      - airflow

networks:
  airflow:
