apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: airflow
  name: airflow-role-admin
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-role-binding
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-role-admin
  apiGroup: rbac.authorization.k8s.io

